import Header from "../components/header";
import Footer from "../components/footer";
import Main from "../components/main";
import Container from "../components/container";
import MainSlider from "../components/mainSlider";
import InfoLink from "../components/infoLink";
import Gapper from "../components/gapper";
import CategoryCard from "../components/categoryCard";
import { smokeyFadeBackground } from "../styles/modules/fadeBackground.module.scss";
import ProductCarousel from "../components/productCarousel";
import PageProductSlider from '../components/pageProductSlider';

export default function HomePage() {
  const infoLinkData = {
    country: "Canada",
    title: "amazon.ca",
    url: "https://amazon.ca",
  };

  const sliderData = [
    {
      url: "deals/mother",
      img: "slide1.jpg",
      alt: "slidr1 image alt",
    },
    {
      url: "#2",
      img: "slide2.jpg",
      alt: "slidr2 image alt",
    },
    {
      url: "#3",
      img: "slide3.jpg",
      alt: "slidr3 image alt",
    },
    {
      url: "#4",
      img: "slide4.jpg",
      alt: "slide4 image alt",
    },
    {
      url: "#5",
      img: "slide5.jpg",
      alt: "slide5 image alt",
    },
    {
      url: "#6",
      img: "slide6.jpg",
      alt: "slide6 image alt",
    },
  ];

  const categoryData1 = [
    {
      type: "card",
      title: "Gaming accessories",
      quadImg: [
        {
          title: "Headsets",
          img: "Fuji_Quad_Headset_1x._SY116_CB667159060_.jpg",
          url: "#productId",
          imgAlt: "Fuji headset image",
        },
        {
          title: "Keyboards",
          img: "Fuji_Quad_Keyboard_1x._SY116_CB667159063_.jpg",
          url: "#productId",
          imgAlt: "Fuji keyboard image",
        },
        {
          title: "Computer mice",
          img: "Fuji_Quad_Mouse_1x._SY116_CB667159063_.jpg",
          url: "#productId",
          imgAlt: "Fuji mouse image",
        },
        {
          title: "Chairs",
          img: "Fuji_Quad_Chair_1x._SY116_CB667159060_.jpg",
          url: "#productId",
          imgAlt: "Fuji mouse image",
        },
      ],
      titleLink: "See more",
      url: "#",
    },
    {
      type: "card",
      title: "Shop deals in Fashion",
      quadImg: [
        {
          title: "Jeans under $50",
          img: "DQC_APR_TBYB_W_BOTTOMS_1x._SY116_CB624172947_.jpg",
          url: "#productId",
          imgAlt: "DQC jean image",
        },
        {
          title: "Tops under $25",
          img: "DQC_APR_TBYB_W_TOPS_1x._SY116_CB623353881_.jpg",
          url: "#productId",
          imgAlt: "DQC Top image",
        },
        {
          title: "Dresses under $30",
          img: "DQC_APR_TBYB_W_DRESSES_1x._SY116_CB623353881_.jpg",
          url: "#productId",
          imgAlt: "DQC dress image",
        },
        {
          title: "Jeans Shoes under $50",
          img: "DQC_APR_TBYB_W_SHOES_1x._SY116_CB624172947_.jpg",
          url: "#productId",
          altImg: "DQC shoes image",
        },
      ],
      titleLink: "See more",
      url: "#",
    },
    {
      type: "card",
      title: "Top Deal",
      img: "41pkIf-VesL._AC_SY230_.jpg",
      imgAlt: "This is alt for image",
      isDiscount: true,
      discount: {
        count: 50,
        isTopDeal: true,
        context: "Shaving and Writing Essentials from Bic",
      },
      titleLink: "See all deals",
      url: "#",
    },
    {
      type: "ads",
      title: "Sign in for the best experience",
      btnUrl: "#",
      btnTitle: "Sign in securely",
      adUrl: "#",
      adImg: "Fuji_D2_45M_en_US_1x._CB418309979_.jpg",
      adImgAlt: "img4 test picture",
    },
  ];

  const categoryData2 = [
    {
      type: "card",
      title: "Easy updates for elevated spaces",
      quadImg: [
        {
          title: "Baskets & hampers",
          img: "2023Q2_GW_EE_LaundryLuxe_D_Quad_186x116._SY116_CB594237035_.jpg",
          url: "#productId",
          imgAlt: "GW_EE Laundry Luxer D_Quad image",
        },
        {
          title: "Hardware",
          img: "2023Q2_GW_EE_Kitchen_D_Quad_186x116._SY116_CB594237035_.jpg",
          url: "#productId",
          imgAlt: "GW_EE Kitchen D_Quad image",
        },
        {
          title: "Accent furniture",
          img: "2023Q2_GW_EE_AccentFurniture_D_Quad_186x116._SY116_CB594237035_.jpg",
          url: "#productId",
          imgAlt: "GW_EE Accent Furniture D_Quad image",
        },
        {
          title: "Chairs",
          img: "2023Q2_GW_EE_Hallway_D_Quad_186x116._SY116_CB594237035_.jpg",
          url: "#productId",
          imgAlt: "GW_EE Hallway D_Quad image",
        },
      ],
      titleLink: "Shop home products",
      url: "#",
    },
    {
      type: "card",
      title: "Refresh your space",
      quadImg: [
        {
          title: "Dining",
          img: "DesktopQuadCat_186x116_LP-HP_B08MYX5Q2W_01.23._SY116_CB619238939_.jpg",
          url: "#productId",
          imgAlt: "DesktopQuadCat LP-HP image",
        },
        {
          title: "Home",
          img: "DesktopQuadCat_186x116_home_B08RCCP3HV_01.23._SY116_CB619238939_.jpg",
          url: "#productId",
          imgAlt: "DesktopQuadCat Home image",
        },
        {
          title: "Kitchen",
          img: "DesktopQuadCat_186x116_kitchen_B0126LMDFK_01.23._SY116_CB619238939_.jpg",
          url: "#productId",
          imgAlt: "DesktopQuadCat image",
        },
        {
          title: "Health and Beauty",
          img: "DesktopQuadCat_186x116_health-beauty_B07662GN57_01.23._SY116_CB619238939_.jpg",
          url: "#productId",
          altImg: "DesktopQuadCat health-beauty image",
        },
      ],
      titleLink: "See more",
      url: "#",
    },
    {
      type: "card",
      title: "Beauty picks",
      img: "Fuji_Dash_Beauty_1x._SY304_CB432774351_.jpg",
      imgAlt: "Fuji Dash Beauty image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Electronics",
      img: "Fuji_Dash_Electronics_1x._SY304_CB432774322_.jpg",
      imgAlt: "Fuji Dash Electronics image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "See more",
      url: "#cardItem",
    },
  ];

  const categoryData3 = [
    {
      type: "card",
      title: "Beauty picks",
      img: "Fuji_Dash_Toys_1X._SY304_CB639759658_.jpg",
      imgAlt: "Fuji dash Toys image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Descover fashion trends",
      img: "mp_20230219_ff_desktopsinglecategory_desktop_379x304_1._SY304_CB612639047_.jpg",
      imgAlt: "two women with yellow and blue dress image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "See more",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Health & Personal Care",
      img: "GW_CONS_AUS_HPC_HPCEssentials_CatCard_Desktop1x._SY304_CB627424361_.jpg",
      imgAlt: "GW CONS AUS HPC HPSEssentials CatCard image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "For your Fitness Needs",
      img: "Fuji_Dash_Fitness_1X._SY304_CB639748186_.jpg",
      imgAlt: "Fuji dash fitness image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop Now",
      url: "#cardItem",
    },
  ];

  const categoryData4 = [
    {
      type: "card",
      title: "Shop activity trackers and smartwatches",
      img: "Fuji_Dash_SmartWatch_1X._SY304_CB639922137_.jpg",
      imgAlt: "Fuji Dash smartwatch 1X image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Shop Laptop & Tablets",
      img: "Fuji_Dash_Laptops_379x304_1X_en_US._SY304_CB418608471_.jpg",
      imgAlt: "Fuji Dash Laptop 1x image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "See more",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Kindle E readers",
      img: "Fuji_Desktop_Dash_Kindle_1x._SY304_CB639752818_.jpg",
      imgAlt: "Fuji Desktop Dash Kindle 1x image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Create with strip lights",
      img: "Fuji_Dash_StripLighting_379x304_1X_en_US._SY304_CB418597476_.jpg",
      imgAlt: "Fuji Dash Strip lighting 1x image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop Now",
      url: "#cardItem",
    },
  ];

  const categoryData5 = [
    {
      type: "card",
      title: "Frequently repurchased in Supplies",
      img: "618OCSwyhfL._AC_SY195_.jpg",
      imgAlt: "MaxiFlex PIP 34-874/L glove image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Top Deal",
      img: "81lKQKYwehL._AC_SY230_.jpg",
      imgAlt: "Gillette Intimate and Venus Trimmer Pack image",
      isDiscount: true,
      discount: {
        count: 40,
        isTopDeal: true,
        context: "Gillette Intimate and Venus Trimmer, Razors and Refills",
      },
      titleLink: "See all deals",
      url: "#",
    },
    {
      type: "card",
      title: "Home refresh ideas",
      img: "XCM_CUTTLE_1559454_3018199_379x304_1X_en_US._SY304_CB592739737_.jpg",
      imgAlt: "Black Faucet image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop now",
      url: "#cardItem",
    },
    {
      type: "card",
      title: "Shop Pet supplies",
      img: "Fuji_Dash_Pets_1X._SY304_CB639746743_.jpg",
      imgAlt: "Brown dog with a white-black cat seat image",
      imgLink: "#imgLink",
      isDiscount: false,
      titleLink: "Shop Now",
      url: "#cardItem",
    },
  ];

  const productCarouselData1 = {
    type: "product",
    isRegular: false,
    isHeaderTitle: true,
    headerTitle: "Gadgets and accessories",
    isLink: false,
    products: [
      {
        id: 1,
        img: "41LDpBUiYkL._AC_SY200_.jpg",
        imgAlt: "Asus TUF Gaming Monitor image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "product title",
      },
      {
        id: 2,
        img: "31-RegrbOmL._AC_SY200_.jpg",
        imgAlt: "GM Genuine parts image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "GM Genuine Parts",
      },
      {
        id: 3,
        img: "41uQytOwFtL._AC_SY200_.jpg",
        imgAlt: "OtterBox Utility image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "OtterBox Utility",
      },
      {
        id: 4,
        img: "41N73lRh-9L._AC_SY200_.jpg",
        imgAlt: "Metra image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Metra",
      },
      {
        id: 5,
        img: "41WkAu6UJLL._AC_SY200_.jpg",
        imgAlt: "MSI Gaming Geforce RTX 3050 8GB image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "MSI Gaming Geforce RTX 3050 8GB",
      },
      {
        id: 6,
        img: "31mEzHVS37L._AC_SY200_.jpg",
        imgAlt: "Tripp Lite TLP604 4Ft image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Tripp Lite TLP604 4Ft",
      },
      {
        id: 7,
        img: "31XG2nkWMjL._AC_SY200_.jpg",
        imgAlt: "Furman AC-215A Compact Power image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Furman AC-215A Compact Power",
      },
      {
        id: 8,
        img: "31lnwnQH7VL._AC_SY200_.jpg",
        imgAlt: "Creative SBS E2900 image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Creative SBS E2900",
      },
      {
        id: 9,
        img: "41EKwVfO5IL._AC_SY200_.jpg",
        imgAlt: "Monoprice DVI-D Single Link Male image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Monoprice DVI-D Single Link Male",
      },
      {
        id: 10,
        img: "31UY41fDmyL._AC_SY200_.jpg",
        imgAlt: "Brady LAT-39-361-1 image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Brady LAT-39-361-1",
      },
      {
        id: 11,
        img: "313Vt-B6HiL._AC_SY200_.jpg",
        imgAlt: "VELCRO Brand-ONE-WRAP image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "VELCRO Brand-ONE-WRAP",
      },
      {
        id: 12,
        img: "41LF1aeNrIL._AC_SY200_.jpg",
        imgAlt: "Fellowes Smart Sultes Laptop image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Fellowes Smart Sultes Laptop",
      },
      {
        id: 13,
        img: "31UfTfHX7TL._AC_SY200_.jpg",
        imgAlt: "Speck Products Presidio2 Grip Samsung Galexy S22 image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Speck Products Presidio2 Grip Samsung Galexy S22",
      },
      {
        id: 14,
        img: "41VSelRmOgL._AC_SY200_.jpg",
        imgAlt: "uxcell Rubber Strain Relief image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "uxcell Rubber Strain Relief",
      },
      {
        id: 15,
        img: "21oNW-+PcOL._AC_SY200_.jpg",
        imgAlt: "Cobra Products LP14SOC Cable image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Cobra Products LP14SOC Cable",
      },
      {
        id: 16,
        img: "41SEX3Fn90L._AC_SY200_.jpg",
        imgAlt: "NHT SuperZero 2.1 Preimium image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "NHT SuperZero 2.1 Preimium",
      },
      {
        id: 17,
        img: "51P6hmE68NL._AC_SY200_.jpg",
        imgAlt: "Bbox Single Sealed 12 Inch image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Bbox Single Sealed 12 Inch",
      },
      {
        id: 18,
        img: "41q9KdrsPaL._AC_SY200_.jpg",
        imgAlt: "LG 32UL950-W 32_Class Ultimate image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "LG 32UL950-W 32_Class Ultimate",
      },
      {
        id: 19,
        img: "31QT7MeYCEL._AC_SY200_.jpg",
        imgAlt: "Pioneer VSX-534 Home Audio image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Pioneer VSX-534 Home Audio",
      },
      {
        id: 20,
        img: "31zXzf5RKRL._AC_SY200_.jpg",
        imgAlt: "APC Rack PDU, Metered, 1U image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "APC Rack PDU, Metered, 1U",
      },
    ],
  };

  const productCarouselData2 = {
    type: "book",
    isHeaderTitle: true,
    headerTitle: "Top Seller in Books for you",
    isRegular: false,
    isLink: false,
    products: [
      {
        id: 101,
        img: "61pOYbCSq4L._AC_SY200_.jpg",
        imgAlt: "Forward Thinking For Your Business book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Forward Thinking For Your Business",
      },
      {
        id: 102,
        img: "71QC2VQfKdL._AC_SY200_.jpg",
        imgAlt:
          "Hold The Line My Story from the heart of the Free... book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Hold The Line My Story from the heart of the Free",
      },
      {
        id: 103,
        img: "61YeOt+1c9L._AC_SY200_.jpg",
        imgAlt: "Courageous Endeavour book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Courageous Endeavour",
      },
      {
        id: 104,
        img: "51bllQ0rwwL._AC_SY200_.jpg",
        imgAlt: "Tommy Transit's Bus Tales book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Tommy Transit's Bus Tales",
      },
      {
        id: 105,
        img: "61CpCRQXV-L._AC_SY200_.jpg",
        imgAlt: "The Glory of Yusuf book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Glory of Yusuf",
      },
      {
        id: 106,
        img: "61tD0RD6sGL._AC_SY200_.jpg",
        imgAlt: "Canada Brave New World book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Canada Brave New World",
      },
      {
        id: 107,
        img: "61toBWkmWrL._AC_SY200_.jpg",
        imgAlt: "Well Done book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Well Done",
      },
      {
        id: 108,
        img: "61emxJ-ce4L._AC_SY200_.jpg",
        imgAlt: "Akwesasne Mohawk Social Song and Dances book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Akwesasne Mohawk Social Song and Dances",
      },
      {
        id: 109,
        img: "91vwHMt+x7L._AC_SY200_.jpg",
        imgAlt: "The Legend of Zelda book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Legend of Zelda",
      },
      {
        id: 110,
        img: "71LPmvTHbwL._AC_SY200_.jpg",
        imgAlt: "MCAT book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "MCAT",
      },
      {
        id: 111,
        img: "71Oe52rlngL._AC_SY200_.jpg",
        imgAlt: "The Most Amazing Marketing Book Ever book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Most Amazing Marketing Book Ever",
      },
      {
        id: 112,
        img: "71SN45kkvDL._AC_SY200_.jpg",
        imgAlt: "The Glucose Goddess Method book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Glucose Goddess Method",
      },
      {
        id: 113,
        img: "610Ux13yhpS._AC_SY200_.jpg",
        imgAlt: "Anxiety Rx book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Anxiety Rx",
      },
      {
        id: 114,
        img: "61yIn0OqgpL._AC_SY200_.jpg",
        imgAlt: "Core Joy book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Core Joy",
      },
      {
        id: 115,
        img: "61Xlx5y9emL._AC_SY200_.jpg",
        imgAlt: "Math 3C Renert Aaron book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Math 3C Renert Aaron",
      },
      {
        id: 116,
        img: "51HuAlryNFL._AC_SY200_.jpg",
        imgAlt: "On Love and Death and Belonging book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "On Love and Death and Belonging",
      },
      {
        id: 117,
        img: "61hyIdXWGeL._AC_SY200_.jpg",
        imgAlt: "Math 3D Renert Aaron book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Math 3D Renert Aaron",
      },
      {
        id: 118,
        img: "71c40f3fLCL._AC_SY200_.jpg",
        imgAlt: "Why Doctors Don't Get Rich book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Why Doctors Don't Get Rich",
      },
      {
        id: 119,
        img: "61Sb+8UJUbL._AC_SY200_.jpg",
        imgAlt: "The Family of Insects book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Family of Insects",
      },
      {
        id: 120,
        img: "614H+Ia0evL._AC_SY200_.jpg",
        imgAlt: "The Players of a Builder book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Players of a Builder",
      },
      {
        id: 121,
        img: "81IsKlDYgdL._AC_SY200_.jpg",
        imgAlt: "Let Your Light Shine book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Let Your Light Shine",
      },
      {
        id: 122,
        img: "61ad-ippQVL._AC_SY200_.jpg",
        imgAlt: "Math 4B Renert Aaron book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Math 4B Renert Aaron",
      },
      {
        id: 123,
        img: "61FFdoQi8BL._AC_SY200_.jpg",
        imgAlt: "Math 1B Renert Aaron book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Math 1B Renert Aaron",
      },
      {
        id: 124,
        img: "61nOsjRJVzL._AC_SY200_.jpg",
        imgAlt: "My Transformation Journal book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "My Transformation Journal",
      },
      {
        id: 125,
        img: "611ZidyrEzL._AC_SY200_.jpg",
        imgAlt: "Buddy the Dinosaur book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Buddy the Dinosaur",
      },
      {
        id: 126,
        img: "61YEjnkPxtL._AC_SY200_.jpg",
        imgAlt: "I AM WORTHY book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "I AM WORTHY",
      },
      {
        id: 127,
        img: "41i5REBmrSL._AC_SY200_.jpg",
        imgAlt: "Never Going Back book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Never Going Back",
      },
      {
        img: "61wBkGUoifL._AC_SY200_.jpg",
        id: 128,
        imgAlt: "A Giant in the North Maine Woods book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "A Giant in the North Maine Woods",
      },
      {
        id: 129,
        img: "514ybv+7taL._AC_SY200_.jpg",
        imgAlt: "Reiki The Healing Touch book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Reiki The Healing Touch",
      },
      {
        id: 130,
        img: "61NtwwCZVfL._AC_SY200_.jpg",
        imgAlt: "Self Love Elevated book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Self Love Elevated",
      },
    ],
  };

  const productCarouselData3 = {
    type: "product",
    isRegular: false,
    isHeaderTitle: true,
    headerTitle: "Popular products in Beauty internationally",
    isLink: false,
    products: [
      {
        id: 21,
        img: "61ijcIHUbbL._AC_SY200_.jpg",
        imgAlt:
          "Mielle Organics Rosemary Mint Scalp & Hair Strengthening Oil image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Mielle Organics Rosemary Mint Scalp & Hair Strengthening Oil",
      },
      {
        id: 22,
        img: "71gyn2vWgoL._AC_SY200_.jpg",
        imgAlt: "CeraVe Tinted Sunscreen with SPF 30 image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "CeraVe Tinted Sunscreen with SPF 30",
      },
      {
        id: 23,
        img: "719pUQCxnmL._AC_SY200_.jpg",
        imgAlt: "Waterpik Aquarius Water Flosser Professional image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Waterpik Aquarius Water Flosser Professional",
      },
      {
        id: 24,
        img: "61A+sJ7zDWL._AC_SY200_.jpg",
        imgAlt: "JOESOEF SKIN CARE Sulfur Soap image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "JOESOEF SKIN CARE Sulfur Soap",
      },
      {
        id: 25,
        img: "51LAALy+vwL._AC_SY200_.jpg",
        imgAlt: "ROUND LAB Birch Juice Moisturizing Sunscreen image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "ROUND LAB Birch Juice Moisturizing Sunscreen",
      },
      {
        id: 26,
        img: "61qO-aag2bL._AC_SY200_.jpg",
        imgAlt: "Neutrogena Purescreen+ Tinted Sunscreen image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Neutrogena Purescreen+ Tinted Sunscreen",
      },
      {
        id: 27,
        img: "81dNZ4pqewL._AC_SY200_.jpg",
        imgAlt: "Ambi Even & Clear Fade Cream image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Ambi Even & Clear Fade Cream",
      },
      {
        id: 28,
        img: "71yucxIWbGL._AC_SY200_.jpg",
        imgAlt: "OH! SWEET ART - Edible Petal Dust image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "OH! SWEET ART - Edible Petal Dust",
      },
      {
        id: 29,
        img: "51fQagfGlQL._AC_SY200_.jpg",
        imgAlt: "Lumineux Teeth Whitening Strips 7 Treatments image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Lumineux Teeth Whitening Strips 7 Treatments",
      },
      {
        id: 30,
        img: "71+CaUj9EtL._AC_SY200_.jpg",
        imgAlt: "Nizoral Anti-Dandruff Shampoo with 1% Ketoconazole image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Nizoral Anti-Dandruff Shampoo with 1% Ketoconazole",
      },
      {
        id: 31,
        img: "81L8Qmoa7xL._AC_SY200_.jpg",
        imgAlt:
          "CeraVe 100% Mineral Sunscreen SPF 50 | Face Sunscreen with Zinc Oxide & Titanium Dioxide image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "CeraVe 100% Mineral Sunscreen SPF 50 | Face Sunscreen with Zinc Oxide & Titanium Dioxide",
      },
      {
        id: 32,
        img: "71l5PzOBvWL._AC_SY200_.jpg",
        imgAlt:
          "Certain Dri Prescription Strength Clinical Antiperspirant Roll-On Deodorant image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Certain Dri Prescription Strength Clinical Antiperspirant Roll-On Deodorant",
      },
      {
        id: 33,
        img: "71SmBhXzwnL._AC_SY200_.jpg",
        imgAlt:
          "Neutrogena Hydro Boost Hyaluronic Acid Facial Moisturizer with Broad Spectrum SPF 50 Sunscreen image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Neutrogena Hydro Boost Hyaluronic Acid Facial Moisturizer with Broad Spectrum SPF 50 Sunscreen",
      },
      {
        id: 34,
        img: "51eJ3Wbi1CL._AC_SY200_.jpg",
        imgAlt: "CeraVe Body Wash with Salicylic Acid image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "CeraVe Body Wash with Salicylic Acid",
      },
      {
        id: 35,
        img: "51FDQ4URb8L._AC_SY200_.jpg",
        imgAlt: "Samnyte Hair Wax Stick, Wax Stick for Hair Slick Stick image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Samnyte Hair Wax Stick, Wax Stick for Hair Slick Stick",
      },
      {
        id: 36,
        img: "81GYltqM5HL._AC_SY200_.jpg",
        imgAlt:
          "Biore UV Aqua Rich Watery 50 g Sunscreen SPF 50 + / PA ++++ image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Biore UV Aqua Rich Watery 50 g Sunscreen SPF 50 + / PA ++++",
      },
      {
        id: 37,
        img: "617J3FspKwL._AC_SY200_.jpg",
        imgAlt: "NATURE WELL Clinical Retinol Advanced Moisture Cream image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "NATURE WELL Clinical Retinol Advanced Moisture Cream",
      },
      {
        id: 38,
        img: "41B8vDMnHHL._AC_SY200_.jpg",
        imgAlt: "ISNTREE Hyaluronic Acid Watery Sun Gel 50ml 1.69fl.oz image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "ISNTREE Hyaluronic Acid Watery Sun Gel 50ml 1.69fl.oz",
      },
      {
        id: 39,
        img: "71rapNz9xBL._AC_SY200_.jpg",
        imgAlt:
          "Undefined Beauty R&R Sun Serum Tinted Mineral Broad Spectrum Sunscreen image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Undefined Beauty R&R Sun Serum Tinted Mineral Broad Spectrum Sunscreen",
      },
      {
        id: 40,
        img: "71A-OkDQNAL._AC_SY200_.jpg",
        imgAlt:
          "SeoulCeuticals Korean Skin Care Beauty - 20% Vitamin C Hyaluronic Acid Serum image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "SeoulCeuticals Korean Skin Care Beauty - 20% Vitamin C Hyaluronic Acid Serum",
      },
      {
        id: 41,
        img: "51eiNHvdPEL._AC_SY200_.jpg",
        imgAlt:
          "Differin Acne Skin Care Set, Differin Gel 3 Step Regimen, Acne Treatment, Sunscreen image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Differin Acne Skin Care Set, Differin Gel 3 Step Regimen, Acne Treatment, Sunscreen",
      },
      {
        id: 42,
        img: "71MO9L6fe-L._AC_SY200_.jpg",
        imgAlt:
          "Hawaiian Tropic SPF 4 Sunscreen, Protective Dark Tannning Sunscreen Lotion 8 Ounces image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Hawaiian Tropic SPF 4 Sunscreen, Protective Dark Tannning Sunscreen Lotion 8 Ounces",
      },
      {
        id: 43,
        img: "41T+wF5mzKL._AC_SY200_.jpg",
        imgAlt: "Caro White Lightening Beauty Cream 500 ml image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Caro White Lightening Beauty Cream 500 ml",
      },
      {
        id: 44,
        img: "710dwZWgv2L._AC_SY200_.jpg",
        imgAlt:
          "Abib Quick Sunstick Protection Bar SPF50+ 0.78 Oz / 22g I Sun Protection image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Abib Quick Sunstick Protection Bar SPF50+ 0.78 Oz / 22g I Sun Protection",
      },
      {
        id: 45,
        img: "61mEC3VhXIL._AC_SY200_.jpg",
        imgAlt:
          "Advanced Clinicals Retinol Body Lotion Moisturizer Face Lotion & Body Cream image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Advanced Clinicals Retinol Body Lotion Moisturizer Face Lotion & Body Cream",
      },
      {
        id: 46,
        img: "51mEmDBAqFL._AC_SY200_.jpg",
        imgAlt: "SKIN1004 Hyalu-CICA Water-fit Sun Serum 1.69 fl. oz image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "SKIN1004 Hyalu-CICA Water-fit Sun Serum 1.69 fl. oz",
      },
      {
        id: 47,
        img: "71Z-Dmc7RoL._AC_SY200_.jpg",
        imgAlt:
          "CeraVe Moisturizing Cream | Body and Face Moisturizer for Dry Skin image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "CeraVe Moisturizing Cream | Body and Face Moisturizer for Dry Skin",
      },
      {
        id: 48,
        img: "519qaXPakML._AC_SY200_.jpg",
        imgAlt: "Hawaiian Tropic Mineral Powder Sunscreen Brush, SPF 30 image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Hawaiian Tropic Mineral Powder Sunscreen Brush, SPF 30",
      },
      {
        id: 49,
        img: "71TAYmz9znL._AC_SY200_.jpg",
        imgAlt: "PanOxyl 10% Acne Foaming Wash 5.5 Ounce image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "PanOxyl 10% Acne Foaming Wash 5.5 Ounce",
      },
      {
        id: 50,
        img: "71fyxuOu-yL._AC_SY200_.jpg",
        imgAlt:
          "Organic Aloe Vera Gel from freshly cut 100% Pure Aloe - Big 12oz image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Organic Aloe Vera Gel from freshly cut 100% Pure Aloe - Big 12oz",
      },
    ],
  };

  const productCarouselData4 = {
    type: "product",
    isRegular: true,
    isHeaderTitle: true,
    headerTitle: "Deal Under 25$",
    isLink: true,
    linkInfo: {
      title: "See more",
      url: "#",
    },
    products: [
      {
        id: 51,
        img: "31t6E0EsnQL._AC_SY200_.jpg",
        imgAlt: "Neutrogena Fragrance-Free Body Oil Light Sesame Formula image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 15.49,
        discount: { count: 22, isTopDeal: false },
        title: "Neutrogena Fragrance-Free Body Oil Light Sesame Formula",
      },
      {
        id: 52,
        img: "51jLoGfBwrL._AC_SY200_.jpg",
        imgAlt:
          "SAS Survival Handbook, Third Edition: The Ultimate Guide to Surviving Anywhere image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 23.99,
        discount: { count: 35, isTopDeal: false },
        title:
          "SAS Survival Handbook, Third Edition: The Ultimate Guide to Surviving Anywhere",
      },
      {
        id: 53,
        img: "51uamwnnEyL._AC_SY200_.jpg",
        imgAlt: "OGX Extra Strength Damage Remedy image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 17.98,
        discount: { count: 22, isTopDeal: false },
        title: "OGX Extra Strength Damage Remedy",
      },
      {
        id: 54,
        img: "51gCrqjIHlL._AC_SY200_.jpg",
        imgAlt: "The True Love Experiment Hardcover image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 27.99,
        discount: { count: 43, isTopDeal: false },
        title: "The True Love Experiment Hardcover",
      },
      {
        id: 55,
        img: "41OHtuW7j+L._AC_SY200_.jpg",
        imgAlt:
          "The Art of Clear Thinking: A Stealth Fighter Pilot's Timeless Rules image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 29.0,
        discount: { count: 31, isTopDeal: false },
        title:
          "The Art of Clear Thinking: A Stealth Fighter Pilot's Timeless Rules",
      },
      {
        id: 56,
        img: "31kAbHK2GoL._AC_SY200_.jpg",
        imgAlt:
          "Design Essentials Peppermint & Aloe TherapeuticsSoothing Scalp Tonic image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 11.67,
        discount: { count: 18, isTopDeal: false },
        title:
          "Design Essentials Peppermint & Aloe TherapeuticsSoothing Scalp Tonic",
      },
      {
        id: 57,
        img: "61K8iw-FrHL._AC_SY200_.jpg",
        imgAlt: "Hydro Swirl Spinning Sprinkler image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 19.99,
        discount: { count: 19, isTopDeal: false },
        title: "Hydro Swirl Spinning Sprinkler",
      },
      {
        id: 58,
        img: "51MemyB9NuL._AC_SY200_.jpg",
        imgAlt: "Unicorn Academy: Rainbow of Adventure Boxed Set image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 23.96,
        discount: { count: 48, isTopDeal: false },
        title: "Unicorn Academy: Rainbow of Adventure Boxed Set",
      },
      {
        id: 59,
        img: "51BgYBpb5wL._AC_SY200_.jpg",
        imgAlt:
          "World War II: The Definitive Visual History from Blitzkrieg to the Atom Bomb image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 40.0,
        discount: { count: 41, isTopDeal: false },
        title:
          "World War II: The Definitive Visual History from Blitzkrieg to the Atom Bomb",
      },
      {
        id: 60,
        img: "51m66FN-XlL._AC_SY200_.jpg",
        imgAlt: "Star Trek: Lower Decks - Season Two image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 31.99,
        discount: { count: 35, isTopDeal: false },
        title: "Star Trek: Lower Decks - Season Two",
      },
      {
        id: 61,
        img: "51JqtRoDtcL._AC_SY200_.jpg",
        imgAlt: "Rick Steves Belgium: Bruges, Brussels image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 21.99,
        discount: { count: 20, isTopDeal: false },
        title: "Rick Steves Belgium: Bruges, Brussels",
      },
      {
        id: 62,
        img: "51i75e4FPlL._AC_SY200_.jpg",
        imgAlt:
          "Recipes from the World of Tolkien: Inspired by the Legends Hardcover image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 28.99,
        discount: { count: 24, isTopDeal: false },
        title:
          "Recipes from the World of Tolkien: Inspired by the Legends Hardcover",
      },
      {
        id: 63,
        img: "41kQCepiZhL._AC_SY200_.jpg",
        imgAlt: "Colageina 10 Glissé Instant Wrinkle Remover image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 21.99,
        discount: { count: 11, isTopDeal: false },
        title: "Colageina 10 Glissé Instant Wrinkle Remover",
      },
      {
        id: 64,
        img: "31v1AWjr4eL._AC_SY200_.jpg",
        imgAlt: "Callaway Swing Easy Golf Swing Trainer Aid, Orange image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 19.99,
        discount: { count: 35, isTopDeal: false },
        title: "Callaway Swing Easy Golf Swing Trainer Aid, Orange",
      },
      {
        id: 65,
        img: "31X+r-QWtmL._AC_SY200_.jpg",
        imgAlt: "Prince Lionheart Dresser Top Diaper Depot image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 22.99,
        discount: { count: 17, isTopDeal: false },
        title: "Prince Lionheart Dresser Top Diaper Depot",
      },
      {
        id: 66,
        img: "41NrZGA0TCL._AC_SY200_.jpg",
        imgAlt: "Girls Like Girls Hardcover image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 20.0,
        discount: { count: 25, isTopDeal: false },
        title: "Girls Like Girls Hardcover",
      },
      {
        id: 67,
        img: "51AhljgumyL._AC_SY200_.jpg",
        imgAlt: "Just Help!: How to Build a Better World image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 17.99,
        discount: { count: 38, isTopDeal: false },
        title: "Just Help!: How to Build a Better World",
      },
      {
        id: 68,
        img: "51FFBmgJrVL._AC_SY200_.jpg",
        imgAlt:
          "Sistema Microwave Soup Mug with Lid and Steam Release Vent image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 13.99,
        discount: { count: 16, isTopDeal: false },
        title: "Sistema Microwave Soup Mug with Lid and Steam Release Vent",
      },
      {
        id: 69,
        img: "41NQXlil-gS._AC_UF226,226_FMjpg_.jpg",
        imgAlt: "LilyAna Naturals Eye Cream image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 24.99,
        discount: { count: 32, isTopDeal: false },
        title: "LilyAna Naturals Eye Cream",
      },
      {
        id: 70,
        img: "41Lh0-CPmFL._AC_UF226,226_FMjpg_.jpg",
        imgAlt: "MelodySusie Electric Nail Drill Machine 11 in 1 Kit image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 29.99,
        discount: { count: 30, isTopDeal: false },
        title: "MelodySusie Electric Nail Drill Machine 11 in 1 Kit",
      },
    ],
  };

  const productCarouselData5 = {
    type: "product",
    isRegular: true,
    isHeaderTitle: true,
    headerTitle: "Deals on electronics, gadgets & accessories",
    isLink: true,
    linkInfo: {
      title: "Explore all deals",
      url: "#",
    },
    products: [
      {
        id: 71,
        img: "41RPcAW0b8L._AC_SY200_.jpg",
        imgAlt:
          "ASUS BE24EQK 23.8” Business Monitor with 1080P Full HD IPS image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 169.0,
        discount: { count: 18, isTopDeal: false },
        title: "ASUS BE24EQK 23.8” Business Monitor with 1080P Full HD IPS",
      },
      {
        id: 72,
        img: "41WkAu6UJLL._AC_SY200_.jpg",
        imgAlt: "MSI Gaming GeForce RTX 3050 8GB GDDR6 128-Bit image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 294.32,
        discount: { count: 25, isTopDeal: false },
        title: "MSI Gaming GeForce RTX 3050 8GB GDDR6 128-Bit",
      },
      {
        id: 73,
        img: "3145szSi9kL._AC_SY200_.jpg",
        imgAlt:
          "Speck Products Balance Folio iPad (2019/2020) Case and Stand image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 19.27,
        discount: { count: 22, isTopDeal: false },
        title: "Speck Products Balance Folio iPad (2019/2020) Case and Stand",
      },
      {
        id: 74,
        img: "41lfRtmuqyL._AC_SY200_.jpg",
        imgAlt:
          "uxcell a13051400ux0579 Plastic Shell Audio Speaker Cable Banana Connector Black Red image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 5.99,
        discount: { count: 8, isTopDeal: false },
        title:
          "uxcell a13051400ux0579 Plastic Shell Audio Speaker Cable Banana Connector Black Red",
      },
      {
        id: 75,
        img: "51xRK+iwxDL._AC_SY200_.jpg",
        imgAlt: "Cooler Master MasterAir MA610P RGB CPU Air Cooler image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 60.0,
        discount: { count: 18, isTopDeal: false },
        title: "Cooler Master MasterAir MA610P RGB CPU Air Cooler",
      },
      {
        id: 76,
        img: "41W6iPnMh2L._AC_SY200_.jpg",
        imgAlt: "Sangean DDR-63 All-in-One Table Top with WiFi Internet image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 339.95,
        discount: { count: 17, isTopDeal: false },
        title: "Sangean DDR-63 All-in-One Table Top with WiFi Internet",
      },
      {
        id: 77,
        img: "21dmZWbranL._AC_SY200_.jpg",
        imgAlt: "GM Genuine Parts 15201407 Rear Radio Speaker image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 40.49,
        discount: { count: 48, isTopDeal: false },
        title: "GM Genuine Parts 15201407 Rear Radio Speaker",
      },
      {
        id: 78,
        img: "41a9Bb1aKIL._AC_SY200_.jpg",
        imgAlt: "JVC HA-V570 Supra-Aural Headphones image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 19.95,
        discount: { count: 25, isTopDeal: false },
        title: "JVC HA-V570 Supra-Aural Headphones",
      },
      {
        id: 79,
        img: "41oF7UtRG5L._AC_SY200_.jpg",
        imgAlt: "Freightliner 5.25 Inch Coaxial Speaker - 22-43130-001 image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 57.12,
        discount: { count: 26, isTopDeal: false },
        title: "Freightliner 5.25 Inch Coaxial Speaker - 22-43130-001",
      },
      {
        id: 80,
        img: "51tw4etoXSL._AC_SY200_.jpg",
        imgAlt: "Earthquake Sound MiNi D1000.4 (Gen 2) Stereo Class image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 180.32,
        discount: { count: 11, isTopDeal: false },
        title: "Earthquake Sound MiNi D1000.4 (Gen 2) Stereo Class",
      },
      {
        id: 81,
        img: "41e0O4mW9GL._AC_SY200_.jpg",
        imgAlt:
          "Humminbird CC ICE Soft Sided Carrying Case for Flashers with No Shuttle image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 54.99,
        discount: { count: 15, isTopDeal: false },
        title:
          "Humminbird CC ICE Soft Sided Carrying Case for Flashers with No Shuttle",
      },
      {
        id: 82,
        img: "41IQSIWhqNL._AC_SY200_.jpg",
        imgAlt:
          "Prime Wire & Cable PB8100X2 6-Outlet Power Strip with Right Angle Plug image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 21.49,
        discount: { count: 45, isTopDeal: false },
        title:
          "Prime Wire & Cable PB8100X2 6-Outlet Power Strip with Right Angle Plug",
      },
      {
        id: 83,
        img: "31gOVkZ7RmL._AC_SY200_.jpg",
        imgAlt: "SureCall 2' SC-400 Ultra Low-Loss Coax Cable image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 19.2,
        discount: { count: 17, isTopDeal: false },
        title: "SureCall 2' SC-400 Ultra Low-Loss Coax Cable",
      },
      {
        id: 84,
        img: "51RsbERSq3L._AC_SY200_.jpg",
        imgAlt:
          "Design Engineering 050199 Boom Mat Speaker Performance Kit image",
        isPrice: true,
        isDiscount: true,
        isTitle: true,
        price: 22.7,
        discount: { count: 17, isTopDeal: false },
        title: "Design Engineering 050199 Boom Mat Speaker Performance Kit",
      },
    ],
  };

  const productCarouselData6 = {
    type: "product",
    isRegular: false,
    isHeaderTitle: true,
    headerTitle: "New international customers purchased",
    isLink: false,
    products: [
      {
        id: 85,
        img: "81qo19353yL._AC_SY200_.jpg",
        imgAlt: "Clear Care Plus Cleaning Solution with Lens Case image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Clear Care Plus Cleaning Solution with Lens Case",
      },
      {
        id: 86,
        img: "71-GCIBN8wL._AC_SY200_.jpg",
        imgAlt:
          "PanOxyl Acne Foaming Wash Benzoyl Peroxide 10% Maximum Strength Antimicrobial image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "PanOxyl Acne Foaming Wash Benzoyl Peroxide 10% Maximum Strength Antimicrobial",
      },
      {
        id: 87,
        img: "51uebuBULdL._AC_SY200_.jpg",
        imgAlt: "Umary Hyaluronic Acid 30 Caplets 850 mg image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Umary Hyaluronic Acid 30 Caplets 850 mg",
      },
      {
        id: 88,
        img: "71XXh2t8guL._AC_SY200_.jpg",
        imgAlt: "My Suitcase: Nii Sookayis Paperback image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "My Suitcase: Nii Sookayis Paperback",
      },
      {
        id: 89,
        img: "61YcMiBeYsL._AC_SY200_.jpg",
        imgAlt: "Trade Up book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Trade Up",
      },
      {
        id: 90,
        img: "41i5REBmrSL._AC_SY200_.jpg",
        imgAlt: "Never Going Back: The Gordon Ferguson Story image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Never Going Back: The Gordon Ferguson Story",
      },
      {
        id: 91,
        img: "71oVA1y3BHL._AC_SY200_.jpg",
        imgAlt:
          "Gold Bond Age Renew Retinol Overnight Body & Face Lotion image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Gold Bond Age Renew Retinol Overnight Body & Face Lotion",
      },
      {
        id: 92,
        img: "51Ski-M7vgL._AC_SY200_.jpg",
        imgAlt:
          "More than Gold: Reflections on Living in Glorious Freedom image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "More than Gold: Reflections on Living in Glorious Freedom",
      },
      {
        id: 93,
        img: "61TGJKUMfCL._AC_SY200_.jpg",
        imgAlt: "SOLARAY Tongkat Ali 400 mg image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "SOLARAY Tongkat Ali 400 mg",
      },
      {
        id: 94,
        img: "71EvfFtt-XL._AC_SY200_.jpg",
        imgAlt:
          "Bloom Nutrition Super Greens Powder Smoothie & Juice Mix image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Bloom Nutrition Super Greens Powder Smoothie & Juice Mix",
      },
      {
        id: 95,
        img: "51LevSjhgsL._AC_SY200_.jpg",
        imgAlt:
          "In Christ: 25 Meditations for Your Personal Transformation image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "In Christ: 25 Meditations for Your Personal Transformation",
      },
      {
        id: 96,
        img: "51VlG-Mz7cL._AC_SY200_.jpg",
        imgAlt: "Hismile v34 Colour Corrector image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Hismile v34 Colour Corrector",
      },
    ],
  };

  const productCarouselData7 = {
    type: "product",
    isRegular: false,
    isHeaderTitle: true,
    headerTitle: "International top seller in Kitchen",
    isLink: false,
    products: [
      {
        id: 97,
        img: "71JTkkNTBsL._AC_SY200_.jpg",
        imgAlt: "Syngenta - Advion Evolution Cockroach Gel 4 Tips image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Syngenta - Advion Evolution Cockroach Gel 4 Tips",
      },
      {
        id: 98,
        img: "61bkLmKirCL._AC_SY200_.jpg",
        imgAlt: "Dr.Pen Adjustable Microneedling Derma Stamp image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Dr.Pen Adjustable Microneedling Derma Stamp",
      },
      {
        id: 99,
        img: "61fakPR+MOL._AC_SY200_.jpg",
        imgAlt:
          "Technology vs. Humanity: The coming clash between man and machine image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Technology vs. Humanity: The coming clash between man and machine",
      },
      {
        id: 100,
        img: "71m743LFESL._AC_SY200_.jpg",
        imgAlt: "RMFLEX Kukaflex Forte 30 tabletas image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "RMFLEX Kukaflex Forte 30 tabletas",
      },
      {
        id: 101,
        img: "61pOYbCSq4L._AC_SY200_.jpg",
        imgAlt:
          "Forward Thinking For Your Business: It's not who you know in business book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "Forward Thinking For Your Business: It's not who you know in business",
      },
      {
        id: 109,
        img: "91vwHMt+x7L._AC_SY200_.jpg",
        imgAlt: "The Legend of Zelda™: Tears of the Kingdom book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "The Legend of Zelda™: Tears of the Kingdom",
      },
      {
        id: 110,
        img: "71LPmvTHbwL._AC_SY200_.jpg",
        imgAlt: "MCAT Complete 7-Book Subject Review 2023-2024 books image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "MCAT Complete 7-Book Subject Review 2023-2024",
      },
      {
        id: 111,
        img: "71Oe52rlngL._AC_SY200_.jpg",
        imgAlt: "More than 350 inspiring ideas! book image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title:
          "The Most Amazing Marketing Book Ever: More than 350 inspiring ideas!",
      },
      {
        id: 134,
        img: "81S7jJk9hxL._AC_SY200_.jpg",
        imgAlt: "Franklin Sports Soccer Shin Guards for Youth + Adults image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Franklin Sports Soccer Shin Guards for Youth + Adults",
      },
      {
        id: 139,
        img: "51LrsAC9AOL._AC_SY200_.jpg",
        imgAlt: "JISULIFE Handheld Mini Fan, 3 IN 1 Hand Fan image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "JISULIFE Handheld Mini Fan, 3 IN 1 Hand Fan",
      },
      {
        id: 140,
        img: "511zdBa2lLL._AC_SY200_.jpg",
        imgAlt: "Lann's Linens - 90 x 156 Premium Tablecloth image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Lann's Linens - 90 x 156 Premium Tablecloth",
      },
      {
        id: 141,
        img: "91C5l82rgdL._AC_SY200_.jpg",
        imgAlt: "600 Piece Silver Dinnerware Set image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "600 Piece Silver Dinnerware Set",
      },
      {
        id: 142,
        img: "7140TguNvFL._AC_SY200_.jpg",
        imgAlt: "Greater Goods Nutrition Food Scale image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Greater Goods Nutrition Food Scale",
      },
      {
        id: 143,
        img: "61SWaYy7AvL._AC_SY200_.jpg",
        imgAlt: "OXO SteeL Double Jigger image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "OXO SteeL Double Jigger",
      },
      {
        id: 144,
        img: "81h7SBztTUL._AC_SY200_.jpg",
        imgAlt: "Fullstar Vegetable Chopper - Spiralizer Vegetable Slicer image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Fullstar Vegetable Chopper - Spiralizer Vegetable Slicer",
      },
      {
        id: 145,
        img: "71sfGeMtEgL._AC_SY200_.jpg",
        imgAlt: "Ninja NC299AMZ CREAMi Ice Cream Maker image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Ninja NC299AMZ CREAMi Ice Cream Maker",
      },
      {
        id: 146,
        img: "81sbYnOkg2L._AC_SY200_.jpg",
        imgAlt: "Alpha Grillers Instant Read Meat Thermometer for Grill and Cooking image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Alpha Grillers Instant Read Meat Thermometer for Grill and Cooking",
      },
      {
        id: 147,
        img: "81S-k9wCDyL._AC_SY200_.jpg",
        imgAlt: "Mr Miracle 7 Inch Paper Hot Dog Tray in Kraft Paper image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Mr Miracle 7 Inch Paper Hot Dog Tray in Kraft Paper",
      },
      {
        id: 148,
        img: "7105g3SZ4GL._AC_SY200_.jpg",
        imgAlt: "Yogurt Maker Automatic Digital Yoghurt Maker Machine with 8 Glass Jars 48 Ozs image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Yogurt Maker Automatic Digital Yoghurt Maker Machine with 8 Glass Jars 48 Ozs",
      },
      {
        id: 149,
        img: "51Cjfj+zclL._AC_SY200_.jpg",
        imgAlt: "Stainless Steel Inner Pot Replacement Insert Liner Accessory image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "Stainless Steel Inner Pot Replacement Insert Liner Accessory",
      },
      {
        id: 150,
        img: "71wGpsLN4ZL._AC_SY200_.jpg",
        imgAlt: "CAROTE Pots and Pans Set Nonstick image",
        price: 249.0,
        isDiscount: false,
        discount: { count: 40, isTopDeal: false },
        isTitle: false,
        title: "CAROTE Pots and Pans Set Nonstick",
      },
    ],
  };

  return (
    <>
      <Header />
      <Main>
        <Container className={smokeyFadeBackground}>
          <MainSlider data={sliderData} />
          <Gapper style={{ position: "relative", marginTop: "-17rem" }}>
            <InfoLink data={infoLinkData} />
            <CategoryCard data={categoryData1} />
            <CategoryCard data={categoryData2} />
            <ProductCarousel data={productCarouselData1} />
            <ProductCarousel data={productCarouselData2} />
            <CategoryCard data={categoryData3} />
            <ProductCarousel data={productCarouselData3} />
            <ProductCarousel data={productCarouselData4} isRegular={true} />
            <CategoryCard data={categoryData4} />
            <ProductCarousel data={productCarouselData5} isRegular={true} />
            <ProductCarousel data={productCarouselData6} isRegular={true} />
            <CategoryCard data={categoryData5} />
            <ProductCarousel data={productCarouselData7} />
            <PageProductSlider />
          </Gapper>
        </Container>
      </Main>

      <Footer window />
    </>
  );
}
